### ISSUE TITLE
0.3.0 Priority List

### ISSUE THREAD

**Issue by seeReadCode** [roundware/roundware-ios-digita11y#39]
## Sina and Halsey tasks
- Testing interruption of playback
- More pause/resume debugging between rooms

## Build 21 items
- VoiceOver focus after first item playback should shift to item progress, not to navbar back button
- VoiceOver shouldn't double announce modals
- VoiceOver should index Item Label in front of Items not after
- Halsey's Maids recording shouldn't always play first in the Exhibition 3, Kitchen

## Tasks of unknown status
- [ ] Initial asset selection should not fail
- [ ] Should not get an error on the initial project get
- [ ] Should not have a "Loading Stream" lock after returning to roomsview from contribute flow
- [ ] Contribute tag buttons should not horizontally scroll
- [ ] Map button needs label or should be removed
- [ ] Countdown timer label should never say "zero total".  maybe "seconds remaining"?
- [ ] "What item do you want to talk about" should have correctly filtered items in contribute flow.  I'm getting "Kitchen, Plates. The Maids, Historic Utensils, Recipes" after selecting to contribute text for "Balzac in ...Onk's Habit"
- [ ] More pause/resume debugging between rooms
- [ ] Location functionality audit (see RoomsViewController#259, RWFrameworkCoreLocation#31 via addMedia)
- [ ] Pass VoiceOver audit (focus placement on resume, skip?)
- [ ] Corner radius https://developer.apple.com/reference/uikit/uiprogressview consider progress view styling for other status?

## Chris tasks
- [x] Indicating played/contributed on items
- [x] Audio buffer dump test - no good - https://developer.apple.com/reference/avfoundation/avplayer/1390806-replacecurrentitemwithplayeritem https://github.com/roundware/roundware-ios-framework-v2/issues/8
- [x] Voiceover notifications for SVProgress modals 
- [x] Move issues https://github.com/IQAndreas/github-issues-import or https://github.com/trbritt/github-issue-migrate or https://github.com/google/github-issue-mover

## Old Build 17 Tasks
- [x] Room selector needs to pass 5 tap test.  It seems to get thrown off if the left button can be selected and your focus is entering from left.  or vice versa 
- [x] Should not get streamsidfailure when selecting first object item
- [x] Enable/disable More button based on if a currentAsset is set.
- ObjectItem's label should be appended with " completed" if all of its its's assets have been played
- Are contribute tags properly filtered?
- [x] deploy to test stream playback
- [x] Fix remaining framework issues, especially method misses https://github.com/seeRead/roundware-ios-framework-v2/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.3.0
- [x] Double check & test flag/block, any other related logic to be implemented
- [x] Multiline object names or better abbreviation e.g. Rodin object "Assembla... Water Fairy" title 
- [x] contribute flow test
- [x] room item player labels not appearing and need correct order.

## Build 16 Tasks
- [x] Transport buttons should remain enabled after room change
- [x] Timer should be a singleton and should update after transport selections (shouldn't be doubling)
- [x] Progress bar should have square edges
- [x] Progress visual ratio should match timer over total for current asset
- [x] tapping into text/photo/map should not interrupt stream
- [x] Rodin exhibit now seems to be working occassionally
- [x] Tag selection should be immediate (seems to hang on "Loading stream" if in middle of a long asset)
- NOT DOING bc server delay: Temporarily lock item selection from tap so meta data doesn't hit back to currently playing item

## Old Build 16 Observations
- Exhibition 2 has empty Intro room
- Exhibition 2 Gallery 1 then wasn't playing on initial load
- Exhibition 3 dining room has no child tags
- Transport control modal feels disruptive.  Should it be dismissed only by appropriate message in stream meta rather than successful POST?
- Should rooms display as options if there are no items?
- Child assets of Rodin seem to not playing but might just be silent assets? I hear clicking in/out.
- Heartbeat failure message
- Disable map button?
- Flag gets a 403 error

**Comment by seeReadCode** [comment]
Some responses:

* I have tried changing things in the back-end both to simplify as well as to confirm how back-end changes are represented in the UI. Unfortunately, I have not experienced behavior consistent with what I expected, so I am wondering if you could briefly outline the logic behind the display of UI items. 
* I tried to remove the empty Intro room in Exhibition 2 for example and I thought deactivating the Intro UI Item would remove it from the UI, but it didn't. Maybe there is caching? I was able to deactivate Exhibition 2 entirely, which is represented in the UI as greyed out, so that makes sense.
* I am not getting any audio streams playing back, but I can do more testing. It sounds like you are getting audio stream playback that isn't silence, yes?
* The transport control modal just flashes for a split second and is therefore very odd, agreed. In my original instructions, I said "display modal overlay saying “remixing your live audio stream…please hold!” until the next asset’s in-stream metadata is received (this will typically take ~5-7 seconds due to audio buffering)", so yes, we want it displayed until stream metadata indicates it should be hidden.
* yes, display rooms even without options; if UI display is properly controllable from the server, we can easily remove rooms or choose to keep them depending on the situation.
* heartbeat messages are failing or there is an issue with the failure message in the event of failure?
* Flag button 403 may be due to server not being updated. IMA should be keeping it updated, but I have not heard from them regarding this process.
* not sure what you mean by "location option" and "location detection flow". we decided to not tackle the automatic location and subsequent PATCHing of the stream as a result at this point, but perhaps I'm misunderstanding your comment...

**Comment by seeReadCode** [comment]
@hburgund I think we need to have a chat about what your expectations are for the UI as far as how back end changes should effect it.  Please drop me a note re: when you'd have time.

More or less, from roundware, I have a tree of a project's UIGroups of UIitems each pointing to a Tag (which in turn refer to a set of assets).  I check the index and mode to situate the UIItems and then use the active flag to determine whether they are displayed.  See the README data model section for the related taxonomy on the UI side.  But yes, this whole tree is grabbed when project is selected. Oh, and exhibits are hidden (but not rooms) if they have no children, because the next view would crash without the necessary ui items.

I could also stand to get some input on why certain some tags don't seem to be triggering asset playback.

One of the Maids asset seems to play every time I start a stream now despite not being selected...

**Comment by seeReadCode** [comment]
Sure, sounds like a good idea to chat directly; I'll send you some times via email.

I installed the newest build and am still not getting any audible stream audio, so it has not been possible for me to do much debugging wrt how things are setup on the server. I'm guessing the server-side content structure is a big part, if not all, of the problem; I'm sure we can make some good progress chatting directly. Thanks.

**Comment by seeReadCode** [comment]
@hburgund @sinabahram my working task list has been updated above.

**Comment by seeReadCode** [comment]
All the of the active issues from https://github.com/seeRead/roundware-ios-digita11y and https://github.com/seeRead/roundware-ios-framework-v2/ have been transferred.  Some of the closed issues for the app have not transferred but I don't want to risk making a big mess of the issue tracker.  From here on out, I plan on updating issues only on the roundware repos (and code wherever I can).

A quick note on pulling issues over: I didn't find a solution that did everything I wanted.

- https://github-issue-mover.appspot.com/ or https://github.com/google/github-issue-mover - This one seems to be popular but only goes one by one and I didn't have high enough permissions to access the roundware repo to create the issues (I can't create labels or milestones either).
- https://github.com/t1bb4r/github-issue-migrate - This is what I used but it times out in the middle of importing issues over, and seems to have some issues with timestamps, and doesn't close out old issues with cross-references
- https://github.com/IQAndreas/github-issues-import - my comp is still installing python3 in order to try this one.

**Comment by seeReadCode** [comment]
@sinabahram @hburgund build 21 has gone out on crashlytics/beta/fabric/whatever you want to call it with this commit https://github.com/seeRead/roundware-ios-digita11y/commit/8655dd0671fa0a9c210de5b7507e3bd81f656642

I'm getting the stream on my device.  And I have updated this thread with items related to build 21.

**Comment by hburgund** [comment]
installed. are we muting the audio from the device speaker on purpose? I am getting no audio unless headphones are plugged in. Perhaps we made this decision a while back, but given that it clearly confused me(!), I think it might not be the best idea.

In any case, the good news is that I am getting audio and can now actually test things properly, which I will do ASAP.

**Comment by seeReadCode** [comment]
I get audio on device without headphones.

**Comment by hburgund** [comment]
interesting...no idea why that behavior isn't consistent, but clearly it is confusing! Let's try to get more test on other devices as maybe it's just something with my old phone or something. No need to waste effort debugging until we have more info on the extent of the issue.
